### ISSUE TITLE
Complete react component prop audit 

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/okrs#125]

**Comment by mattrosno** [comment]
How will the team know that this is completed? Where will the audit results be available? What are the measurable milestones (Key Results) that you'll need to accomplish along the way?

**Comment by tw15egan** [comment]
Results will be available in the Notion document 

https://www.notion.so/carbondesignsystem/3d691f70a7934d4485e6d596974fbbaa?v=8ee7547d09a7431a929b760e54d557a6
