### ISSUE TITLE
Ensure components match design spec / complete component audit 

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/okrs#126]

**Comment by mattrosno** [comment]
I like this, but it may be a little too lofty. Are there specific components that you'd like to bring into design and code alignment? Or a certain number of components that you'd like to hit?

**Comment by mattrosno** [comment]
Cascaded from #85

**Comment by tw15egan** [comment]
It seems the designers are just going alphabetically, so I am knocking them out as the issues pop up
