### ISSUE TITLE
Restructure topics and reference out to other sources

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/okrs#158]
This is about defining the scope of what is included and what is not. 
1. Organize the content of what will be included
2. Reference out to other important sources within the company such as Brand Center, the brand systems, IBM Style, and IBM Design Language, where appropriate.

**Comment by janchild** [comment]
This is about defining the scope of what is included and what is not. 
1. Organize the content of what will be included
2. Reference out to other important sources within the company such as Brand Center, the brand systems, IBM Style, and IBM Design Language, where appropriate. 

Note to talk with Mike about what to include from the typography

**Comment by mattrosno** [comment]
Any carbon-website issues that you want to cross-link (via comment)? Now that you have scoped?
