### ISSUE TITLE
Revise baseline guidance for Principles and Language

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/okrs#160]
Update existing topics with fresh content for the following

Overview
  Content foundations
  Voice and tone
  Writing for accessibility

Writing style
  Capitalization
  Simple writing
  Conversational style
  Inclusive terminology
  Pronouns
  Active and passive voice

The PR with these changes can be seen here: 
https://github.com/carbon-design-system/carbon-website/pull/1910

**Comment by mattrosno** [comment]
Awesome to see complete KRs! Do you have a PR or something to share as evidence of completion? (So others can learn more about what this completed effort looks like?)

**Comment by janchild** [comment]
> Awesome to see complete KRs! Do you have a PR or something to share as evidence of completion? (So others can learn more about what this completed effort looks like?)

Just updated the description, @mattrosno. Unfortunately we can't link the PR in the **Linked pull requests** section because it's in a different repo.

**Comment by mattrosno** [comment]
@janchild I was thinking more copy/paste the PR URL here into a comment. So there's a loose association between the efforts. Nothing official "closing this PR will close this issue".

**Comment by janchild** [comment]
Closing this PR closes the key result:
carbon-design-system/carbon-website#1910
