### ISSUE TITLE
The team is fully bought into OKR culture and practice, with clear impact on team's delivery

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/okrs#19]
OKR evolution

1. OKRs will engage the team and have a positive impact on our momentum and delivery
2. The team is fully bought into OKR culture and practice, with clear impact on team's delivery

**Comment by vpicone** [comment]
Potentially trap #5 https://www.whatmatters.com/resources/google-okr-playbook/#classic-okr-writing-mistakes-and-traps
