### ISSUE TITLE
Release cycles deliver high-quality outcomes to end users, with minimal disruption, and validation measures in place

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/okrs#23]
Title evolution...

1. Release cycles are focused, and deliver high-quality outcomes to end users
2. Release deliver high-quality outcomes to end users, with minimal disruption, and validation measures in place

**Comment by vpicone** [comment]
Potentially trap #2 https://www.whatmatters.com/resources/google-okr-playbook/#classic-okr-writing-mistakes-and-traps
