### ISSUE TITLE
Understand how Carbon is being used among strategic IBM offering adoption opportunities

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/okrs#27]

**Comment by vpicone** [comment]
Potentially [trap #2](https://www.whatmatters.com/resources/google-okr-playbook/#classic-okr-writing-mistakes-and-traps): Business-as-usual OKRs

> OKRs are often written principally based on what the team believes it can achieve without changing anything they’re currently doing, as opposed to what the team or its customers really want.

**Comment by mattrosno** [comment]
@joshblack your comment:

> This one feels a bit globby / this is what any team would do. Would be cool to make it unique to carbon / what we’re trying to do. What is something discrete that we could deliver for this as a team?

This team objective reminds me of company objectives to the likes of "increase revenue". That objective by itself doesn't mean much. It becomes meaningful once you accompany it with key results.

Looking at the 3 team objectives as they stand, #29 seems to be about assets, this one about tools/services, and #28 about measuring what we do. All three seem to have good cascade potential to firm up the objectives?
