### ISSUE TITLE
Put measures in place so Q4 OKRs can be more data-driven

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/okrs#28]

**Comment by vpicone** [comment]
What were you thinking of lumping into the "nearly" category?

**Comment by mattrosno** [comment]
@joshblack your comment:

> At the end of Q3 it’d be great to say that we know who is using our stuff, how are they using it, what version are they on, etc. This could address questions around how people are using our stuff (if at all) and would speak to Phil’s prompt from today around how to we measure adoption of what we ship, both existing work and newly introduced work.

Success and failure can be measured many ways. Maybe that's implementing and using a usability study process. Maybe that's by raw adoption.

What is a key result that could cascade to system squad with the "how"? How we are to measure adoption to understand success/failure of efforts?
