### ISSUE TITLE
Enable consumption of community-generated assets that are built with Carbon

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/okrs#29]

**Comment by vpicone** [comment]
Potentially [trap #2](https://www.whatmatters.com/resources/google-okr-playbook/#classic-okr-writing-mistakes-and-traps): Business-as-usual OKRs

> OKRs are often written principally based on what the team believes it can achieve without changing anything they’re currently doing, as opposed to what the team or its customers really want.

**Comment by shinytoyrobots** [comment]
I think that's a fair comment, @vpicone. How might we rephrase or refine this so that it's, instead, forcing us to reach for something greater. Specifically focused on the openness/community aspect. The community aspect is the bit that I don't think is the "business as usual" piece, so maybe we could emphasize that more.

**Comment by vpicone** [comment]
@shinytoyrobots then we should hone in on a tangible, objective, and unambiguous projects would make Carbon more community focused. 
O: Increase community engagement at Carbon
kr: Rebrand support to engagement on the website, resurface this content to make it easily discoverable
kr: By q4 reach out to 75% of IBM's must-win products to see if/how they use Carbon
kr: Add focal designers to the website (literally any of @jeanservaas stuff we presented to Phil would be great here)

**Comment by shinytoyrobots** [comment]
@mattrosno - we decided to close this at the team level, right, as captured in #51 at the squad level?
