### ISSUE TITLE
The Carbon website messaging is repositioned to actively encourage consumption, productive use, and contribution

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/okrs#66]
- Update the homepage messaging of Carbon as an open, service-oriented group to support ease of use and contribution by IBMers (Jan, Jeannie, Mike)
- Revised mission statement has been validated by the Carbon team and published on site
- “About Carbon” pages updated and published with new content supportive of objective
- Documented a defined communication strategy, including talking points for team members
- Validate value by conducted surveys/interviews with key users — where do people want to go next (Jillian, SUS?)

**Comment by mattrosno** [comment]
@janchild I'm going to close this in favor of new OKRs for Q4.

Part of the OKR process that we'll do this quarter is self-assessment scoring. Score definitions here: https://github.com/carbon-design-system/okrs/labels

I'll put `score: 0.5` on this given great progress on our about / team pages. I understand you wanted to flip this to Q4 when priorities changed. We should have updated the OKR to reflect that back then. All good!
