### ISSUE TITLE
Gain Phil's preliminary agreement on the team's and system squad's top-line Q3 and 2020 OKRs by 7/10/20

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/okrs#7]

**Comment by shinytoyrobots** [comment]
As we discussed, I don't think this needs Phil's feedback at this point. I think we need to demonstrate impact to him, rather than talking about OKRs in the abstract.

**Comment by mattrosno** [comment]
@shinytoyrobots I agree. I'll drop this KR.
