### ISSUE TITLE
Publish scope of next major release by 11/13/20

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/okrs#86]

**Comment by mattrosno** [comment]
Reach out to Fahad O, Dave B, and team on Carbon Grid future direction (e.g. what grid enhancements, or new technologies, are in plan for next major release.)

**Comment by mattrosno** [comment]
@alisonjoseph @joshblack @janchild can we also include naming for this release and how we communicate it? @mjabbink recommends we confirm release naming and comms strategy with Phil G outside of the weekly playbacks.

**Comment by joshblack** [comment]
**Note: anything in this post is WIP and can be changed**

Just to add some more info on the dev side, here is the initial draft for the release table based on planned package changes:

| Package                  | Old   | New   | Notes            |
| ------------------------ | ----- | ----- | ---------------- |
| @carbon/colors           | v10.X | v10.X | No changes       |
| @carbon/elements         | v10.X | v11.X | Breaking changes       |
| @carbon/grid             | v10.X | v11.X | Breaking changes |
| @carbon/icons            | v10.X | v11.X | Breaking changes |
| @carbon/icons-react      | v10.X | v11.X | Breaking changes |
| @carbon/pictograms       | v11.X | v11.X | No changes       |
| @carbon/pictograms-react | v11.X | v11.X | No changes       |
| @carbon/layout           | v10.X | v10.X | No changes       |
| @carbon/motion           | v10.X | v10.X | No changes       |
| @carbon/type             | v10.X | v11.X | Breaking changes |
| @carbon/themes           | v10.X | v11.X | Breaking changes |
| carbon-components        | v10.X | v11.X | Breaking changes |
| carbon-components-react  | v10.X | v11.X | Breaking changes |
| @carbon/react            | N/A   | v1.0  | New package      |
