### ISSUE TITLE
Document token naming conventions

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/okrs#87]

**Comment by mattrosno** [comment]
@aagonzales can you share Notion URL?

**Comment by aagonzales** [comment]
List of new tokens: 
https://www.notion.so/carbondesignsystem/List-of-to-be-tokens-031c30ccd0e142858c79b33ad2fdc92e

Naming convention documentation: 
https://www.notion.so/carbondesignsystem/Naming-convention-ff1fb11cf7cc4b1899d558b842855d55

**Comment by mattrosno** [comment]
@aagonzales thanks!
